### ISSUE TITLE
Metadata in exports to identify author, original ShaderFrog URL, version.

### ISSUE THREAD

**Issue by bhouston** [DelvarWorld/ShaderFrog-Runtime#11]
The following would be really useful metadata in each export:

Author username (thus able to get ShaderFrog profile url)
ShaderFrog URL to shader, or enough data that one can reconstruct it, like a shader ID.
Revision of the shader on ShaderFrog (because there will be a lot of different versions flying around.)

**Comment by bhouston** [comment]
The reason I ask if that if we import a ShaderFrog resource into Clara, it would be nice to have the ability to fork or see it on ShaderFrog with just a click -- this data would make that possible.

**Comment by DelvarWorld** [comment]
good idea. i'm thinking export the id and username, and give the runtime the ability to get the url with runtime.getShaderFrogLink( shaderId ) or something like that - that way if the URLs ever changed they won't be hard coded into json, and the latest version of the runtime will generate them correctly. what do you think?

I think revisions should be a separate issue, since it entails a bit more work independent of the exported format.

**Comment by bhouston** [comment]
Username and Shader ID is minimally sufficient.

If you do not have revision numbers, it may be useful to just add a date/time of export.

Maybe you want to include a format version number of the JSON somewhere so that when you make breaking changes there is a way to detect it.

**Comment by DelvarWorld** [comment]
ok, I added a `url` field to the shader that links to the full url, and a user object that has username and url. http://shaderfrog.com/api/download?shaderId=123&preview=1 I'll add revision to the file as part of the revision ticket work
